#!/bin/sh

# This script was originally taken from this link below:
# https://faq.i3wm.org/question/239/how-do-i-suspendlockscreen-and-logout.1.html
#
# The script works for linux distributions with systemd.

lock() {
    i3lock --ignore-empty-password
}

case "${1}" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: ${0} {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
